const dummyMails = [
  {
    id: 1,
    subject: "Flash Sale: 20% off",
    body: "This is a dummy mail.",
    sender: "puma@air.com",
    receiver: "jenthomasjames123@air.com",
    visible: true,
  },
  {
    id: 2,
    subject: "Top companies are hiring!",
    body: "This is a dummy mail.",
    sender: "glassdoor@air.com",
    receiver: "jenthomasjames123@air.com",
    visible: true,
  },
  {
    id: 3,
    subject: "Your credit report is updated.",
    body: "This is a dummy mail.",
    sender: "cred@air.com",
    receiver: "jenthomasjames123@air.com",
    visible: true,
  },
  {
    id: 4,
    subject: "Are you ready for this?",
    body: "This is a dummy mail.",
    sender: "myntra.com",
    receiver: "jenthomasjames123@air.com",
    visible: true,
  },
  {
    id: 5,
    subject: "Just in at CTS",
    body: "This is a dummy mail.",
    sender: "glassdoor@air.com",
    receiver: "jenthomasjames123@air.com",
    visible: true,
  },
  {
    id: 6,
    subject: "Templates of the week",
    body: "This is a dummy mail.",
    sender: "devianart@air.com",
    receiver: "jenthomasjames@air.com",
    visible: true,
  },
];
export default dummyMails;
